accounts/urls.py
from django.conf.urls import url
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"^login/", views.login_view, name="login"),
    url(r"^register/", views.register_view, name="register"),
    url(r'^logout/', views.logout_view, name="logout"),
    url(r'^settings/', views.settings, name="settings"),

]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = "polls"

urlpatterns = [
    url(r"^add/$", views.add, name="add"),
    url(r"^(?P<slug>[\w-]+)/$", views.DetailView.as_view(), name="detail"),
    url(r'/', views.index, name="surveys"),
]

surveys/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import index
from pages import views as page_views
from polls.sitemaps import Poll_Sitemap, AuthSitemap, IndexSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    "polls": Poll_Sitemap(),
    "accounts": AuthSitemap(),
    "index": IndexSitemap(),
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name="home"),
    url(r'^accounts/', include('accounts.urls'), name="accounts"),
    url(r"^polls/", include('polls.urls'), name="polls"),
    url(r'^(?P<url>[-\w]+)/$', page_views.view_page),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

templates/auth_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand js-scroll-trigger" href="/">

        Surveys
        </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">



        {% if user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="/admin">Yönetim</a>
        </li>
        {% endif %}


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-poll"></i> Anket
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'polls:add' %}">Anket Oluştur</a>

          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i> Hesap
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'accounts:settings' %}">Hesap Ayarları</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Çıkış Yap</a>

          </div> 

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Diğer Sayfalar
          </a>
          <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
          {% for i in NAV_PAGES %}
              <a class="dropdown-item" href="/{{ i.url }}">{{ i.name }}</a>
          {% endfor %}
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Ne aramıştınız?" aria-label="Search" name="q" value="{{ request.GET.q }}">
            <button class="btn btn-black my-2 my-sm-0" type="submit"><i class="fas fa-search"></i> Arama</button>
      </form>
  </div>
</nav>

templates/base.html
{# Ramazan Emre Osmanoğlu | Created with love... #}

<!DOCTYPE html>
<html lang="tr">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %} Surveys |{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Ücretsiz anket sitesi.">
    <meta name="keywords" content="surveys, anket, anketler, ücretsiz, Ramazan Osmanoğlu, anket sitesi, anket yapma sitesi, anket oylama">
    <meta name="abstract" content="Anketler oluşturun, yorum yapın, anketleri oylayın ve daha fazlasını yapın!">
    <meta name="theme-color" content="#37474F" />


    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>


    <link rel="stylesheet" href="{% static 'vendor/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/all.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/style.css' %}">

    <meta name="google-site-verification" content="FhDAs8KMho49IBMCht2RdyRvFEvorGGYHZoq0T-yLms" />

</head>
<body>


{# MESSAGE SYSTEM #}

{% block messages %}
{% include 'messages.html' %}
{% endblock %}

<div class="jumbotron bg-transparent">
    {% block content %}

    {% endblock %}

</div>


{% block footer %}
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Telif Hakkı &copy; Ramazan Emre Osmanoğlu 2019</p>
      <p class="m-0 text-center text-white">Created with <i class="fas fa-heart"></i> and Django</p>

    </div>
    <!-- /.container -->
  </footer>
{% endblock %}



<script src="{% static 'vendor/jquery.js' %}"></script>
<script src="{% static 'vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/all.js' %}"></script>

<script>
    $(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

</body>
</html>

templates/defnavbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand js-scroll-trigger" href="/">
        Surveys
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">

        <form class="form-inline">
          <a href="{% url 'accounts:register' %}"><button class="btn btn-outline-success" type="button">Kaydol</button></a>
          <a href="{% url 'accounts:login' %}"> <button class="btn btn-outline-primary" type="button">Giriş Yap</button></a>
        </form>
      </ul>
    </div>
</nav>

templates/index.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} Ana Sayfa {% endblock %}


{% block content %}

{% if user.is_authenticated %}
{% include 'auth_navbar.html' %}

{% else %}
{% include 'defnavbar.html' %}
{% endif %}


<br> <br>
{% block messages %}
  {{ block.super }}
{% endblock %}
{% if alerts %}
{% for i in alerts %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
  {{ i.text }} <a class="alert-link" href="/{{ i.url }}">{{ i.title }}</a>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
{% if polls %}

{% for poll in polls %}
<div class="jumbotron text-white bg-transparent">
  <div class="container">
    <h1 class="display-5">{{ poll.title }}</h1>
    {% if poll.explanation %}
    <p class="lead">{{ poll.explanation }}</p>
    {% endif %}
    <p class="date">{{ poll.date }}</p>

    {% if poll.author.rank == 1 %}
    <p class="author-1" onclick="gouser('{{ poll.author.get_absolute_url }}');">{{ poll.author.username }}</p>
    {% elif poll.author.rank == 2 %}
    <p class="author-2" onclick="gouser('{{ poll.author.get_absolute_url }}');">{{ poll.author.username }}</p>
    {% elif poll.author.rank == 3 %}
    <p class="author-3" onclick="gouser('{{ poll.author.get_absolute_url }}');">{{ poll.author.username }}</p>
    {% elif poll.author.rank == 4 %}
    <p class="author-4" onclick="gouser('{{ poll.author.get_absolute_url }}');">{{ poll.author.username }}</p>
    {% elif poll.author.rank == 5 %}
    <p class="author-5" onclick="gouser('{{ poll.author.get_absolute_url }}');"><i class="fas fa-crown"></i> {{ poll.author.username }}</p>
    {% elif poll.author.rank == 6 %}
    <p class="author-6" onclick="gouser('{{ poll.author.get_absolute_url }}');"><i class="fas fa-crown"></i> {{ poll.author.username }} <i class="fas fa-crown"></i></p>
    {% endif %}

    <a href="{{ poll.get_absolute_url }}">
      <button class="btn btn-black" type="button"> <i class="fas fa-poll"></i> Ankete Git</button>
    </a>

  </div>
</div>
{% endfor %}
{% endif %}

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

    function gouser(url) {
      windows.location = url;
    }
</script>

{% endblock %}

templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="{{ message.tags }}" role="alert">{{ message }}</div>
{% endfor %}
{% endif %}

templates/page_view.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} {{ page.name }} {% endblock %}

{% block defnavbar %} {% endblock %}

{% block content %}
<br> <br>
{{ page.page_content|safe|escape }}

{% endblock %}

{% block footer %} {% endblock %}

templates/welcome.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} Ana Sayfa {% endblock %}


{% block content %}
{% include 'defnavbar.html' %}

{% block messages %} {{ block.super }} {% endblock %}

<div class="jumbotron text-white bg-transparent">
    <div class="container">
        <h1 class="display-3">Anket Dünyası</h1>
        <p class="lead">
            Her konuda anketler bulabileceğin, insanlarla yarışabileceğin, <br>
            anketler yaparak zaman geçirebileceğin dünyaya hoşgeldin!
        </p>
        <a href="{% url 'polls:surveys' %}"> <button class="btn btn-black" type="button">Anketlere Git</button></a>
    </div>
</div>

<div class="jumbotron text-white bg-transparent">
    <div class="container">
        <h1 class="display-3"> Surveys Yaz Güncellemesi </h1>
        <p class="lead"> Yaz Güncellemesiyle beraber gelen yenilikleri görmek için kaydol.</p>
        <a href="{% url 'accounts:register' %}"> <button class="btn btn-black" type="button">Kaydol</button></a>
    </div>
</div>

<div class="jumbotron text-white bg-transparent">
    <div class="container">
        <h1 class="display-3"> Surveys Nedir? </h1>
        <p class="lead">Surveys, kullanıcıların anket yaptığı, diğer anketleri oyladığı,
            sitedeki aktivitelerine göre puan kazanıp yükseldiği, anketleri eğlenceli bir hale
            sokmuş olan bir internet sitesidir.
        </p>
        <a href="{% url 'accounts:register' %}"> <button class="btn btn-black" type="button">Kaydol</button></a>
    </div>
</div>

{% endblock %}